name: "Create Tag"
description: "Create and optionally push a git tag with a given pattern"
inputs:
  project:
    description: "Project name"
    required: true
  version:
    description: "Project version"
    required: true
  tag-pattern:
    description: "Pattern for tag name, e.g. v{project}-{version}"
    required: true
  dry-run:
    description: "If true, do not push tag, just print what would be done"
    required: false
    default: 'false'
  working-directory:
    description: "Working directory for the repository"
    required: false
    default: '.'

outputs:
  tag-name:
    description: "The name of the created tag"
    value: ${{ steps.create-tag.outputs.tag-name }}

runs:
  using: "composite"
  steps:
    - name: Create and push tag
      id: create-tag
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        TAG_PATTERN: ${{ inputs.tag-pattern }}
        DRY_RUN: ${{ inputs.dry-run }}
        PROJECT: ${{ inputs.project }}
        VERSION: ${{ inputs.version }}
      run: |
        TAG_NAME=$(echo "$TAG_PATTERN" | sed "s/{project}/$PROJECT/g" | sed "s/{version}/$VERSION/g")
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        echo "Creating tag: $TAG_NAME"
        git tag -a "$TAG_NAME" -m "Release $PROJECT v$VERSION

            This release was automatically created by GitHub Actions.
            
            Project: $PROJECT
            Version: $VERSION
            Commit: $(git rev-parse HEAD)
            "
        
        if [ "$DRY_RUN" = "true" ]; then
          echo "[DRY_RUN] Would push tag: $TAG_NAME"
        else
          git push origin "$TAG_NAME"
        fi
        
        echo "tag-name=$TAG_NAME" >> $GITHUB_OUTPUT