name: "Publish .NET App"
description: "Publish a .NET application with specified configuration"
inputs:
  output-path:
    description: "Output directory for published files"
    required: false
  project-path:
    description: "Path to the project file (.csproj)"
    required: true
  version:
    description: "Version to use for the publish"
    required: false
  configuration:
    description: "Publish configuration (Release, Debug, etc.)"
    required: false
    default: 'Release'
  dotnet-versions:
    description: "Versions of .NET to install"
    required: false
    default: |
      10.0.x
      9.0.x
      8.0.x
  publish-args:
    description: "Additional arguments for dotnet publish command"
    required: false
    default: '--self-contained true --runtime win-x64 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishTrimmed=true -p:PublishReadyToRun=false'

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-versions }}

    - name: Publish
      shell: bash
      run: |
        publish_args="--configuration ${{ inputs.configuration }}"

        if [[ -n "${{ inputs.version }}" ]]; then
          publish_args="$publish_args -p:Version=${{ inputs.version }} -p:AssemblyVersion=${{ inputs.version }} -p:FileVersion=${{ inputs.version }}"
        fi

        if [[ -n "${{ inputs.publish-args }}" ]]; then
          publish_args="$publish_args ${{ inputs.publish-args }}"
        fi

        if [[ -n "${{ inputs.output-path }}" ]]; then
          publish_args="$publish_args --output ${{ inputs.output-path }}"
        fi

        dotnet publish ${{ inputs.project-path }} $publish_args
