name: "Generate Changelog"
description: "Generate a changelog using git-chglog"
inputs:
  git-chglog-version:
    description: "Version of git-chglog to install"
    required: false
    default: 'latest'
  tag:
    description: "Git tag to generate changelog for"
    required: false
  next-tag:
    description: "Next tag for unreleased changes"
    required: false
  title:
    description: "Title for the changelog"
    required: true
  config-file:
    description: "Path to git-chglog configuration file"
    required: false
    default: '.chglog/config.yml'
  template-file:
    description: "Path to git-chglog template file"
    required: false
    default: '.chglog/CHANGELOG.tpl.md'
  repository-url:
    description: "Repository URL for links (auto-detected if not provided)"
    required: false
  output-file:
    description: "Output file for the changelog"
    required: false
  format:
    description: "Output format (markdown, json, etc.)"
    required: false
    default: 'markdown'

outputs:
  changelog-content:
    description: "Generated changelog content"
    value: ${{ steps.generate.outputs.changelog }}
  changelog-file:
    description: "Path to the generated changelog file"
    value: ${{ inputs.output-file }}

runs:
  using: "composite"
  steps:
    - name: Install git-chglog
      shell: bash
      run: |
        if ! command -v git-chglog &> /dev/null; then
          echo "Installing git-chglog..."
          
          # Detect OS and architecture
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          
          case $ARCH in
            x86_64) ARCH="amd64" ;;
            aarch64|arm64) ARCH="arm64" ;;
            armv7l) ARCH="armv7" ;;
          esac
          
          if [[ "${{ inputs.git-chglog-version }}" == "latest" ]]; then
            # Get latest version from GitHub API
                  VERSION=$(curl -s https://api.github.com/repos/git-chglog/git-chglog/releases/latest | grep '"tag_name":' | sed -E 's/.*"v?([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          else
            VERSION="${{ inputs.git-chglog-version }}"
          fi
          
          # Download and install
          DOWNLOAD_URL="https://github.com/git-chglog/git-chglog/releases/download/v${VERSION}/git-chglog_${VERSION}_${OS}_${ARCH}.tar.gz"
          
          echo "Downloading git-chglog from: $DOWNLOAD_URL"
          curl -sL "$DOWNLOAD_URL" | tar xz
          
          # Make executable and move to PATH
          chmod +x git-chglog
          sudo mv git-chglog /usr/local/bin/
          
          echo "git-chglog installed successfully"
        else
          echo "git-chglog already installed"
        fi
        
        git-chglog --version

    - name: Initialize git-chglog config (if not exists)
      shell: bash
      run: |
        echo "[git-chglog] Checking if config file exists: ${{ inputs.config-file }}"
        if [[ ! -f "${{ inputs.config-file }}" ]]; then
          echo "[git-chglog] Creating default git-chglog configuration..."
          config_dir="$(dirname "${{ inputs.config-file }}")"
          mkdir -p "$config_dir"
          echo "[git-chglog] Created config directory: $config_dir"

          # Copy default config and substitute repository URL
          action_dir="${{ github.action_path }}"
          config_template="$action_dir/templates/default-config.yml"
          echo "[git-chglog] Using config template: $config_template"

          if [[ -f "$config_template" ]]; then
            # Replace repository URL placeholder
            template_filename="$(basename \"${{ inputs.template-file }}\")"
            repo_url="${{ inputs.repository-url }}"
            if [[ -z "$repo_url" ]]; then
              repo_url="${{ github.server_url }}/${{ github.repository }}"
            fi
            echo "[git-chglog] Substituting title: ${{ inputs.title }}"
            echo "[git-chglog] Substituting repo_url: $repo_url"
            echo "[git-chglog] Substituting template_filename: $template_filename"
            
            sed -e "s|{{ .Info.Title }}|${{ inputs.title }}|g" \
                -e "s|{{ .Info.RepositoryURL }}|$repo_url|g" \
                -e "s|{{ .Info.TemplateFile }}|$template_filename|g" \
                "$config_template" > "${{ inputs.config-file }}"
            echo "[git-chglog] Config file created: ${{ inputs.config-file }}"
          else
            echo "[git-chglog] Config template not found: $config_template"
          fi

          if [[ ! -f "${{ inputs.template-file }}" ]]; then
            # Create default template
            template_filename="$(basename \"${{ inputs.template-file }}\")"
            template_file="$action_dir/templates/$template_filename"
            template_dir="$(dirname \"${{ inputs.template-file }}\")"
            echo "[git-chglog] Checking for template file: $template_file"
            echo "[git-chglog] Creating template directory: $template_dir"
            mkdir -p "$template_dir"
            if [[ -f "$template_file" ]]; then
              echo "[git-chglog] Copying template file to: $template_dir"
              cp -p "$template_file" "$template_dir"
              echo "[git-chglog] Template file copied: $template_dir/$template_filename"
            else
              echo "[git-chglog] Template file not found: $template_file"
            fi
          else
            echo "[git-chglog] Template file already exists: ${{ inputs.template-file }}"
          fi

          echo "[git-chglog] Default git-chglog template created"
        else
          echo "[git-chglog] Config file already exists: ${{ inputs.config-file }}"
        fi

    - name: Generate changelog
      id: generate
      shell: bash
      run: |
        # Build git-chglog command
        cmd="git-chglog"
        
        if [[ -f "${{ inputs.config-file }}" ]]; then
          cmd="$cmd --config ${{ inputs.config-file }}"
        fi
        
        if [[ -n "${{ inputs.next-tag }}" ]]; then
          cmd="$cmd --next-tag ${{ inputs.next-tag }}"
        fi
        
        if [[ -n "${{ inputs.tag }}" ]]; then
          cmd="$cmd ${{ inputs.tag }}"
        fi
        
        echo "Running: $cmd"
        
        # Generate changelog
        changelog_content=$($cmd)
        
        # Save to file only if output-file input provided
        if [[ -n "${{ inputs.output-file }}" ]]; then
          echo "$changelog_content" > "${{ inputs.output-file }}"
          echo "Changelog generated and saved to: ${{ inputs.output-file }}"
        else
            echo "Input 'output-file' non fourni: le changelog ne sera pas écrit dans un fichier."
        fi
        
        # Output for other steps
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$changelog_content" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
